name: Deploy Node.js HTTP Server to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > "${{ secrets.EC2_KEY_NAME }}"
          chmod 600 "${{ secrets.EC2_KEY_NAME }}"

      - name: Test SSH connectivity
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_KEY_NAME }}" "${{ secrets.SERVER_USER }}"@"${{ secrets.SERVER_HOST }}" "echo SSH connection successful"

      - name: Copy app files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_KEY_NAME }}" "${{ secrets.SERVER_USER }}"@"${{ secrets.SERVER_HOST }}" "mkdir -p ~/app"
          scp -o StrictHostKeyChecking=no -i "${{ secrets.EC2_KEY_NAME }}" index.js "${{ secrets.SERVER_USER }}"@"${{ secrets.SERVER_HOST }}":~/app/index.js

      - name: Install Node.js on EC2 (if needed) and run server
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_KEY_NAME }}" "${{ secrets.SERVER_USER }}"@"${{ secrets.SERVER_HOST }}" << 'EOF'
            if ! command -v node > /dev/null; then
              if [ -f /etc/debian_version ]; then
                curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
                sudo apt-get install -y nodejs
              else
                curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
                sudo yum install -y nodejs
              fi
            fi

            sudo lsof -t -i tcp:3000 | xargs -r kill -9
            nohup node ~/app/index.js > ~/app/server.log 2>&1 &
          EOF
